# Header
nav:
  博客: /archives
  分类: /categories
  标签: /tags

# favicon
favicon: images/favicon.ico

# logo
logo: /images/logo.svg

# links
links:
  Github: https://github.com/Lancenas
  抖音: https://douyin.com
  小红书: https://www.xiaohongshu.com
  知乎: https://www.zhihu.com/
  Weibo: https://weibo.com


# analytics
google_analytics: UA-149148285-1
baidu_analytics:

# mathjax
fancybox: true

# mathjax
mathjax: true

# echarts
echarts: true

# busuanzi
busuanzi: true

# mermaid
mermaid:
  enable: true
  # Available themes: default | dark | forest | neutral
  theme: default

# giscus
giscus:
  enable:
  repo:
  repo_id:
  category:
  category_id:
  mapping:

# maple
maple:
  enable: true
  # fall leaf count
  count: 10
  # 0-1
  speed: 0.5

