# Header
nav:
  博客: /archives/
  分类: /category/
  标签: /tag/

# favicon
favicon: images/favicon-16.ico

# logo
logo: /images/sites-logo.svg

# links
links:
  Github: https://github.com/Lancenas
  # ZhiHu:
  # Twitter:
  # Weibo:

# analytics
google_analytics: UA-149148285-1
baidu_analytics:

# mathjax
fancybox: true

# mathjax
mathjax: true

# echarts
echarts: true

# busuanzi
busuanzi: true

# mermaid
mermaid:
  enable: true
  # Available themes: default | dark | forest | neutral
  theme: default

# giscus
giscus:
  enable: true
  repo: Lancenas/Sites-Giscus
  repo_id: R_kgDOMVUxEQ
  category: Announcements
  category_id: DIC_kwDOMVUxEc4CgvWb
  mapping: pathname

# maple
maple:
  enable: true
  # fall leaf count
  count: 10
  # 0-1
  speed: 0.5
